const ERROR_CODE = 400;
const NOT_FOUND_CODE = 404;
const CREATED_CODE = 201;
const INTERNAL_SERVER_ERROR = 500;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const CONFLICT_ERROR = 409;

module.exports = {
  ERROR_CODE,
  NOT_FOUND_CODE,
  CREATED_CODE,
  INTERNAL_SERVER_ERROR,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_ERROR,
  CONFLICT_ERROR,
};